export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
